var legends = [{"Full Form":"Braj Ras Madhuri - Vol 3","Code":"br3"},
               {"Full Form":"Old Braj Ras Madhuri - Vol 3 Ext 1","Code":"or31"},
               {"Full Form":"Old Braj Ras Madhuri - Vol 3","Code":"or3"},
               {"Full Form":"Prem Ras Madira - Viraha Madhuri","Code":"vir"},
               {"Full Form":"Prem Ras Madira - Rasiya Madhuri","Code":"ras"},
               {"Full Form":"Braj Ras Madhuri - Vol 2","Code":"br2"},
               {"Full Form":"Prem Ras Madira - Leela Madhuri","Code":"lee"},
               {"Full Form":"Prem Ras Madira - Prakiran Madhuri","Code":"pra"},
               {"Full Form":"Prem Ras Madira - Nikunj Madhuri","Code":"nik"},
               {"Full Form":"Prem Ras Madira - Maan Madhuri","Code":"maa"},
               {"Full Form":"Prem Ras Madira - Murali Madhuri","Code":"mur"},
               {"Full Form":"Prem Ras Madira - Milan Madhuri","Code":"mil"},
               {"Full Form":"Prem Ras Madira - Holi Madhuri","Code":"hol"},
               {"Full Form":"Prem Ras Madira - Mahasakhi Madhuri","Code":"mah"},
               {"Full Form":"Yugal Shatak - Vol 1","Code":"ys1"},
               {"Full Form":"Yugal Ras - Vol 1","Code":"yr1"},
               {"Full Form":"Braj Ras Madhuri - Vol 1","Code":"br1"},
               {"Full Form":"Prem Ras Madira - Dainya Madhuri","Code":"dai"},
               {"Full Form":"Prem Ras Madira - Siddhant Madhuri","Code":"sid"},
               {"Full Form":"Prem Ras Madira - Krishna Madhuri","Code":"kri"},
               {"Full Form":"Prem Ras Madira - Krishna Bal Madhuri","Code":"kba"},
               {"Full Form":"Prem Ras Madira - Yugal Madhuri","Code":"yug"},
               {"Full Form":"Prem Ras Madira - SadGuru Madhuri","Code":"sad"},
               {"Full Form":"Prem Ras Madira - Radha Madhuri","Code":"rad"},
               {"Full Form":"Yugal Madhuri - Vol 1","Code":"ym1"},
               {"Full Form":"Prem Ras Madira - Aarti Madhuri","Code":"art"},
               {"Full Form":"Leela Maduri Barsana Dham Publication","Code":"lm1"},
               {"Full Form":"Prem Ras Madira - Radha Bal Madhuri","Code":"rba"},
               {"Full Form":"Prem Ras Madira - Dham Madhuri","Code":"dha"},
               {"Full Form":"Old Braj Ras Madira Vol 1","Code":"or1"},
               {"Full Form":"Prem Ras Madira - Prem Madhuri","Code":"pre"},
               {"Full Form":"Radha Krishna Guna Gaan - Vol 1","Code":"rk1"},
               {"Full Form":"Lecture","Code":"lec"},
               {"Full Form":"Radhe Govind Geet","Code":"rgg"},
               {"Full Form":"Shyama Shyam Geet","Code":"ssg"},
               {"Full Form":"Bhakti Shatak","Code":"bs1"},
               {"Full Form":"Krishna Dwadeshi","Code":"kdd"},
               {"Full Form":"Radhe Triadeshi","Code":"rtd"},
               {"Full Form":"Aarti","Code":"art"},
               {"Full Form":"Nam Chanting","Code":"nam"},
               {"Full Form":"Shayeri","Code":"sha"},
               {"Full Form":"Braj Ke Savayi","Code":"bks"},
               {"Full Form":"Question and Answer Session","Code":"qa1"},
               {"Full Form":"General talk","Code":"gen"},
               {"Full Form":"Chantings","Code":"cha"},
               {"Full Form":"Prem Ras Madira - Vol 1","Code":"pr1"},
               {"Full Form":"Prem Ras Madira - Vol 2","Code":"pr2"}] ;